### ISSUE TITLE
Console program for the library

### ISSUE THREAD

**Issue by josecelano** [rurban/libbf#1]
I'm looking for a console program that uses this library to run things like:

```
libbf atan 20 1
```

and get the result of applying the `bf_atan` function to argument `1` showing `20` decimals.

**Comment by rurban** [comment]
There are plenty of bignum calculator programs, easiest probably `bc`. This is just a tiny library.

**Comment by josecelano** [comment]
Thank you. I read `bc` man help but I did not find it, the function is called `a`:

This is the way to do what I asked:
```
echo "scale=10;a(1)" | bc -lq
```
